### PR TITLE
Feature: make overdue completions visible for teachers

### PR DESCRIPTION
**Pull request by kulmann**
This feature makes overdue activity completions visible for teachers by flagging them with a new icon (yellow alarm clock icon) and stating the overdue time (in hours when less than a day, in days otherwise).

Bildschirmfoto 2019-03-18 um 09 20 09

### CODE REVIEW

**Comment by kulmann** [comment]
I would like to bring attention to this PR again. Happy to receive any feedback. Will also do improvements if something is not up to your standards, yet.

@deraadt 
also cc @lucaboesch since you seem to be active here during the past days :-)

**Comment by lucaboesch** [comment]
Thanks @kulmann I just recently was sent to this plugin by a lecturer.
We just adopted it now.
More input may be given by @adpe whose institution has a much broader use, right?

**Comment by kulmann** [comment]
Nice, thanks! @lucaboesch

@deraadt i can open a new PR with a cleaner history as well if you want to have a clean git log.

**Comment by adpe** [comment]
Hi @kulmann 

It seems like a good idea, but I don't know if all people want to have this feature enabled per default. Would be great to have this as an additional setting in `settings.php`.

Further I just want to let you know, that my PR https://github.com/deraadt/moodle-block_completion_progress/pull/47 is has still not activity. Would be great to get here feedback from you and @lucaboesch as well. I think this problem is more urgent than this feature. The plugin at the moment has plain SQL queries, and instead Moodle core functions would be better to get these statuses. I've reworked a lot of code. 

Hope to hear something from @deraadt in future.

HTH,
Adrian

**Comment by deraadt** [comment]
Hi, Benedikt.

Thanks for working on this and sharing your changes. While I can see this might be useful for some, I'm keen to keep the block simple and avoid adding additional states.

Hopefully anyone interested in your addition will be able to merge your changes.

Michael

**Pull request closed without merging**
